- name: "Download Docker installation script"
  shell: 'curl -fsSL https://get.docker.com -o get-docker.sh'
  tags: &docker_related_tags ['docker', 'install']

- name: "Install Docker"
  shell: 'sh get-docker.sh'
  tags: *docker_related_tags
